# Generated by Django 5.2.7 on 2026-02-25 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='football_key',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mistral_key',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
    ]
