# Generated by Django 5.2.7 on 2026-02-25 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_profile_football_key_alter_profile_mistral_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='football_key',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='mistral_key',
        ),
        migrations.AddField(
            model_name='profile',
            name='football_key_encrypted',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='mistral_key_encrypted',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
