# Generated by Django 5.2.7 on 2026-02-25 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_profile_football_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_beta_tester',
            field=models.BooleanField(default=False),
        ),
    ]
